### ISSUE TITLE
Is there any way to make it work on videos?

### ISSUE THREAD

**Issue by ankitdhmn** [PKU-YuanGroup/LLaVA-CoT#13]
I was wondering if the current model could be adapted to process videos instead of images. Any guidance or tips for adapting the model for video data would be greatly appreciated!

Thanks in advance for your help, and kudos again on this amazing project.

**Comment by XuGW-Kevin** [comment]
You may want to use Qwen-VL, InternVL or any other opensource models that support video input.
You can always use our dataset as part of your training data.

**Comment by ankitdhmn** [comment]
Thanks so much for the clarification and the suggestions! I really appreciate you pointing me toward other models. I'll try them out.
