### ISSUE TITLE
Local run instructions please

### ISSUE THREAD

**Issue by ramkumarkoppu** [PKU-YuanGroup/LLaVA-CoT#14]
Hi,

Can you please provide instructions to run this model locally Linux/Mac computer?

**Comment by XuGW-Kevin** [comment]
Hi, to run this model locally on Linux/Mac computer, a good way is to convert the model to GGUF and use ollama.
However, [llama.cpp](https://github.com/ggerganov/llama.cpp) does not support this feature. 
It would be very hard for me to implement this, but it seems that the community has been [working on this](https://github.com/ggerganov/llama.cpp/issues/9643).

**Comment by XuGW-Kevin** [comment]
However, you can try running a quantized version of the model locally. 
I found that the repository at [unslothai](https://github.com/unslothai/unsloth/releases/tag/November-2024) supports quick quantization for using models in the llama-3.2-vision series, though I haven’t tried it myself. 
If you’re willing to give it a try and encounter any issues, I’d be happy to work together to solve them. Thank you for your interest!
