### ISSUE TITLE
What is the final output of LLava-CoT? I used the inference script on HuggingFace but only got the step-by-step outputs as shown below. My input image was a rabbit.

### ISSUE THREAD

**Issue by yisuanwang** [PKU-YuanGroup/LLaVA-CoT#16]
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████| 9/9 [00:02<00:00,  3.32it/s]
Generated Text:
user

What is shown in the picture?assistant

(Here begins the SUMMARY stage) I will analyze the image to identify the subject and provide a detailed description focusing on relevant features. I will then use logical reasoning to confirm the identification and provide the standard answer. (Here ends the SUMMARY stage)

(Here begins the CAPTION stage) The image shows a rabbit with light brown fur, large ears, and whiskers. It is sitting with its body facing the left side of the image. (Here ends the CAPTION stage)

(Here begins the REASONING stage) The image displays a rabbit due to its distinct features: fur, ears, and whiskers. The position and posture of the rabbit, with its body turned to the left, align with the description in the standard answer. (Here ends the REASONING stage)

(Here begins the CONCLUSION stage) The image shows a rabbit sitting with its body facing the left side of the image. (Here ends the CONCLUSION stage)

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modify the setup method to load model shards correctly and add a utility function for shard downloading.

You can review changes in this commit: https://github.com/mnmnk43434/PKU-YuanGroup-LLaVA-CoT-16/commit/0290a1872dd1ade62ee9e74e949c67c5e083f525.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by XuGW-Kevin** [comment]
You've provided the complete output from LLava-CoT. It seems your question was "What is shown in the picture?" and LLaVA-CoT correctly identified that "The image shows a rabbit sitting with its body facing the left side of the image." Of course, you can choose to keep only the part within the conclusion tag, or use the entire output—it's up to you.

**Comment by zibingo** [comment]
> You've provided the complete output from LLava-CoT. It seems your question was "What is shown in the picture?" and LLaVA-CoT correctly identified that "The image shows a rabbit sitting with its body facing the left side of the image." Of course, you can choose to keep only the part within the conclusion tag, or use the entire output—it's up to you.

How to output only the conclusion part

**Comment by XuGW-Kevin** [comment]
> > You've provided the complete output from LLava-CoT. It seems your question was "What is shown in the picture?" and LLaVA-CoT correctly identified that "The image shows a rabbit sitting with its body facing the left side of the image." Of course, you can choose to keep only the part within the conclusion tag, or use the entire output—it's up to you.
> 
> How to output only the conclusion part

The simplest way is to use a regular expression to extract the part within the <CONCLUSION> tag after the output has been generated. If your use case involves providing a service (such as a Gradio app), you can begin outputting content only after detecting the <CONCLUSION> tag.

**Comment by yisuanwang** [comment]
谢谢您的解答！我的问题已解决！
