### ISSUE TITLE
Visualization of the selection process

### ISSUE THREAD

**Issue by LYZ-123-XYZ** [PKU-YuanGroup/LLaVA-CoT#17]
Thank you for your excellent work. I am very interested in the selection process of each step in inference_demo.py. How can I reproduce this selection process in inference_demo.py?

**Comment by XuGW-Kevin** [comment]
Hello, thank you for raising the issue! I'm not entirely sure what you mean specifically, but if you're referring to:

1. **What is the principle behind model selection in the selection process?**
In the current version, we use prompting to let the model make the selection. Of course, more advanced methods, such as employing different models, could also be explored.

2. **How to check the input and output of the model in the selection process and how the selection is made?**
Our code saves logs in a log.jsonl file. You can add a similar log-saving feature in your own code to track this.

3. **How to reproduce this process with your own model?**
If your model also outputs results in stages, you can directly use the same approach. If not, you might consider splitting the output into several sentences or fixed tokens for selection. However, this approach may lack clear semantic meaning, and its effectiveness is uncertain. We believe that semantic segmentation by stages is a key factor for achieving effective results.

Let me know if this clarifies your question or if there's anything else you'd like to discuss!

**Comment by LYZ-123-XYZ** [comment]
Thank you for your reply, it solved my confusion.🙂
