### ISSUE TITLE
Is this project truly following the O1 technical route? 

### ISSUE THREAD

**Issue by justbin-coder** [PKU-YuanGroup/LLaVA-CoT#3]
What are the differences? The O1 route includes post-training and a reflective error correction mechanism.

**Comment by XuGW-Kevin** [comment]
Thanks for your issue! It is just an initial version now, and we're improving our project on at least three aspects:
1. A stronger base model like Qwen2-VL
2. A stronger inference time scaling method like MCTS.
3. You mentioned "a reflective error correction mechanism". Yeah, we are going to support this feature after we find a strong inference time scaling method! We will use a new pair of tag called <REFLECTION></REFLECTION> and we are making progress on this. Stay tuned!

**Comment by ramkumarkoppu** [comment]
Hi, wondering how to fine tune this model using O1 vision as the teacher model, any suggestions please?

**Comment by XuGW-Kevin** [comment]
Hi!
A simple but likely effective approach would be to use O1 to create a new dataset. You can refer to our prompt format for guidance, but perhaps you need to modify it to fit O1's requirement. For example, O1 may ban the output if you mentioned "reasoning process". Then, fine-tune your model using that dataset. However, the computational cost of O1 is significantly higher compared to GPT-4o, and our dataset cost several thousand dollars, so the overall expenses for this process might be much higher.
Hope that helps!
